# Generated by Django 5.0.1 on 2024-02-01 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=100)),
                ('book_genre', models.CharField(max_length=100)),
                ('book_description', models.TextField()),
                ('book_price', models.IntegerField()),
                ('book_coverpage', models.FileField(upload_to='coverpages/')),
                ('book_author', models.CharField(max_length=100)),
                ('book_year', models.IntegerField()),
                ('book_publisher', models.CharField(max_length=100)),
                ('book_stock', models.CharField(max_length=100)),
                ('book_status', models.IntegerField(default=0)),
            ],
        ),
    ]
