# Generated by Django 5.0.1 on 2024-02-04 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_orders_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
